export interface IconDef {
    url: string;
    label: string; // accessible alt text
}

export const ICON_MARKUPS: Record<string, IconDef> = {
    ICON_ALPHA: { url: '/images/Civ5Icon.Alpha.png', label: 'Alpha' },
    ICON_BLOCKADED: { url: '/images/Civ5Icon.Blockaded.png', label: 'Blockaded' },
    ICON_BULLET: { url: '/images/Civ5Icon.Bullet.png', label: 'Bullet' },
    ICON_CAPITAL: { url: '/images/Civ5Icon.Capital.png', label: 'Capital' },
    ICON_CITIZEN: { url: '/images/Civ5Icon.Citizen.png', label: 'Citizen' },
    ICON_CITY_STATE: { url: '/images/Civ5Icon.CityState.png', label: 'CityState' },
    ICON_CONNECTED: { url: '/images/Civ5Icon.Connected.png', label: 'Connected' },
    ICON_CULTURE: { url: '/images/Civ5Icon.Culture.png', label: 'Culture' },
    ICON_DENOUNCE: { url: '/images/Civ5Icon.Denounce.png', label: 'Denounce' },
    ICON_FLOWER: { url: '/images/Civ5Icon.Flower.png', label: 'Flower' },
    ICON_FOOD: { url: '/images/Civ5Icon.Food.png', label: 'Food' },
    ICON_GOLD: { url: './images/Civ5Icon.Gold.png', label: 'Gold' },
    ICON_GOLDEN_AGE: { url: '/images/Civ5Icon.GoldenAge.png', label: 'GoldenAge' },
    ICON_GREAT_ADMIRAL: { url: '/images/Civ5Icon.GreatAdmiral.png', label: 'GreatAdmiral' },
    ICON_GREAT_ARTIST: { url: '/images/Civ5Icon.GreatArtist.png', label: 'GreatArtist' },
    ICON_GREAT_ENGINEER: { url: '/images/Civ5Icon.GreatEngineer.png', label: 'GreatEngineer' },
    ICON_GREAT_GENERAL: { url: '/images/Civ5Icon.GreatGeneral.png', label: 'GreatGeneral' },
    ICON_GREAT_MERCHANT: { url: '/images/Civ5Icon.GreatMerchant.png', label: 'GreatMerchant' },
    ICON_GREAT_MUSICIAN: { url: '/images/Civ5Icon.GreatMusician.png', label: 'GreatMusician' },
    ICON_GREAT_PEOPLE: { url: '/images/Civ5Icon.GreatPeople.png', label: 'GreatPeople' },
    ICON_GREAT_SCIENTIST: { url: '/images/Civ5Icon.GreatScientist.png', label: 'GreatScientist' },
    ICON_GREAT_WRITER: { url: '/images/Civ5Icon.GreatWriter.png', label: 'GreatWriter' },
    ICON_HAPPINESS_1: { url: '/images/Civ5Icon.Happiness1.png', label: 'Happiness1' },
    ICON_HAPPINESS_2: { url: '/images/Civ5Icon.Happiness2.png', label: 'Happiness2' },
    ICON_HAPPINESS_3: { url: '/images/Civ5Icon.Happiness3.png', label: 'Happiness3' },
    ICON_HAPPINESS_4: { url: '/images/Civ5Icon.Happiness4.png', label: 'Happiness4' },
    ICON_IDEOLOGY_AUTOCRACY: { url: '/images/Civ5Icon.IdeologyAutocracy.png', label: 'IdeologyAutocracy' },
    ICON_IDEOLOGY_FREEDOM: { url: '/images/Civ5Icon.IdeologyFreedom.png', label: 'IdeologyFreedom' },
    ICON_IDEOLOGY_ORDER: { url: '/images/Civ5Icon.IdeologyOrder.png', label: 'IdeologyOrder' },
    ICON_INFLUENCE: { url: '/images/Civ5Icon.Influence.png', label: 'Influence' },
    ICON_INQUISITOR: { url: '/images/Civ5Icon.Inquisitor.png', label: 'Inquisitor' },
    ICON_INTERNATIONAL_TRADE: { url: '/images/Civ5Icon.InternationalTrade.png', label: 'InternationalTrade' },
    ICON_INVEST: { url: '/images/Civ5Icon.Invest.png', label: 'Invest' },
    ICON_KAPPA: { url: '/images/Civ5Icon.Kappa.png', label: 'Kappa' },
    ICON_LOCKED: { url: '/images/Civ5Icon.Locked.png', label: 'Locked' },
    ICON_MINUS: { url: '/images/Civ5Icon.Minus.png', label: 'Minus' },
    ICON_MISSIONARY: { url: '/images/Civ5Icon.Missionary.png', label: 'Missionary' },
    ICON_MOVES: { url: '/images/Civ5Icon.Moves.png', label: 'Moves' },
    ICON_MUSHROOM: { url: '/images/Civ5Icon.Mushroom.png', label: 'Mushroom' },
    ICON_OCCUPIED: { url: '/images/Civ5Icon.Occupied.png', label: 'Occupied' },
    ICON_OMEGA: { url: '/images/Civ5Icon.Omega.png', label: 'Omega' },
    ICON_PEACE: { url: '/images/Civ5Icon.Peace.png', label: 'Peace' },
    ICON_PIRATE: { url: '/images/Civ5Icon.Pirate.png', label: 'Pirate' },
    ICON_PLUS: { url: '/images/Civ5Icon.Plus.png', label: 'Plus' },
    ICON_PRODUCTION: { url: '/images/Civ5Icon.Production.png', label: 'Production' },
    ICON_PROPHET: { url: '/images/Civ5Icon.Prophet.png', label: 'Prophet' },
    ICON_PUPPET: { url: '/images/Civ5Icon.Puppet.png', label: 'Puppet' },
    ICON_RANGE_STRENGTH: { url: '/images/Civ5Icon.RangeStrength.png', label: 'RangeStrength' },
    ICON_RAZING: { url: '/images/Civ5Icon.Razing.png', label: 'Razing' },
    ICON_RELIGION: { url: '/images/Civ5Icon.Religion.png', label: 'Religion' },
    ICON_RELIGION_BUDDHISM: { url: '/images/Civ5Icon.ReligionBuddhism.png', label: 'ReligionBuddhism' },
    ICON_RELIGION_CHRISTIANITY: { url: '/images/Civ5Icon.ReligionChristianity.png', label: 'ReligionChristianity' },
    ICON_RELIGION_CONFUCIANISM: { url: '/images/Civ5Icon.ReligionConfucianism.png', label: 'ReligionConfucianism' },
    ICON_RELIGION_HINDUISM: { url: '/images/Civ5Icon.ReligionHinduism.png', label: 'ReligionHinduism' },
    ICON_RELIGION_ISLAM: { url: '/images/Civ5Icon.ReligionIslam.png', label: 'ReligionIslam' },
    ICON_RELIGION_JUDAISM: { url: '/images/Civ5Icon.ReligionJudaism.png', label: 'ReligionJudaism' },
    ICON_RELIGION_ORTHODOX: { url: '/images/Civ5Icon.ReligionOrthodox.png', label: 'ReligionOrthodox' },
    ICON_RELIGION_PANTHEON: { url: '/images/Civ5Icon.ReligionPantheon.png', label: 'ReligionPantheon' },
    ICON_RELIGION_PROTESTANT: { url: '/images/Civ5Icon.ReligionProtestant.png', label: 'ReligionProtestant' },
    ICON_RELIGION_SHINTO: { url: '/images/Civ5Icon.ReligionShinto.png', label: 'ReligionShinto' },
    ICON_RELIGION_SIKHISM: { url: '/images/Civ5Icon.ReligionSikhism.png', label: 'ReligionSikhism' },
    ICON_RELIGION_TAOISM: { url: '/images/Civ5Icon.ReligionTaoism.png', label: 'ReligionTaoism' },
    ICON_RELIGION_TENGRIISM: { url: '/images/Civ5Icon.ReligionTengriism.png', label: 'ReligionTengriism' },
    ICON_RELIGION_ZOROASTRIANISM: { url: '/images/Civ5Icon.ReligionZoroastrianism.png', label: 'ReligionZoroastrianism' },
    ICON_RES_ALUMINUM: { url: '/images/Civ5Icon.ResAluminum.png', label: 'ResAluminum' },
    ICON_RES_BANANA: { url: '/images/Civ5Icon.ResBanana.png', label: 'ResBanana' },
    ICON_RES_CITRUS: { url: '/images/Civ5Icon.ResCitrus.png', label: 'ResCitrus' },
    ICON_RES_COAL: { url: '/images/Civ5Icon.ResCoal.png', label: 'ResCoal' },
    ICON_RES_COPPER: { url: '/images/Civ5Icon.ResCopper.png', label: 'ResCopper' },
    ICON_RES_COTTON: { url: '/images/Civ5Icon.ResCotton.png', label: 'ResCotton' },
    ICON_RES_COW: { url: '/images/Civ5Icon.ResCow.png', label: 'ResCow' },
    ICON_RES_CRAB: { url: '/images/Civ5Icon.ResCrab.png', label: 'ResCrab' },
    ICON_RES_DEER: { url: '/images/Civ5Icon.ResDeer.png', label: 'ResDeer' },
    ICON_RES_DYE: { url: '/images/Civ5Icon.ResDye.png', label: 'ResDye' },
    ICON_RES_FISH: { url: '/images/Civ5Icon.ResFish.png', label: 'ResFish' },
    ICON_RES_FUR: { url: '/images/Civ5Icon.ResFur.png', label: 'ResFur' },
    ICON_RES_GEMS: { url: '/images/Civ5Icon.ResGems.png', label: 'ResGems' },
    ICON_RES_GOLD: { url: '/images/Civ5Icon.ResGold.png', label: 'ResGold' },
    ICON_RES_HORSE: { url: '/images/Civ5Icon.ResHorse.png', label: 'ResHorse' },
    ICON_RES_INCENSE: { url: '/images/Civ5Icon.ResIncense.png', label: 'ResIncense' },
    ICON_RES_IRON: { url: '/images/Civ5Icon.ResIron.png', label: 'ResIron' },
    ICON_RES_IVORY: { url: '/images/Civ5Icon.ResIvory.png', label: 'ResIvory' },
    ICON_RES_JEWELRY: { url: '/images/Civ5Icon.ResJewelry.png', label: 'ResJewelry' },
    ICON_RES_MARBLE: { url: '/images/Civ5Icon.ResMarble.png', label: 'ResMarble' },
    ICON_RES_OIL: { url: '/images/Civ5Icon.ResOil.png', label: 'ResOil' },
    ICON_RES_PEARLS: { url: '/images/Civ5Icon.ResPearls.png', label: 'ResPearls' },
    ICON_RES_PORCELAIN: { url: '/images/Civ5Icon.ResPorcelain.png', label: 'ResPorcelain' },
    ICON_RES_SALT: { url: '/images/Civ5Icon.ResSalt.png', label: 'ResSalt' },
    ICON_RES_SHEEP: { url: '/images/Civ5Icon.ResSheep.png', label: 'ResSheep' },
    ICON_RES_SILK: { url: '/images/Civ5Icon.ResSilk.png', label: 'ResSilk' },
    ICON_RES_SILVER: { url: '/images/Civ5Icon.ResSilver.png', label: 'ResSilver' },
    ICON_RES_SPICES: { url: '/images/Civ5Icon.ResSpices.png', label: 'ResSpices' },
    ICON_RES_STONE: { url: '/images/Civ5Icon.ResStone.png', label: 'ResStone' },
    ICON_RES_SUGAR: { url: '/images/Civ5Icon.ResSugar.png', label: 'ResSugar' },
    ICON_RES_TRUFFLES: { url: '/images/Civ5Icon.ResTruffles.png', label: 'ResTruffles' },
    ICON_RES_URANIUM: { url: '/images/Civ5Icon.ResUranium.png', label: 'ResUranium' },
    ICON_RES_WHALE: { url: '/images/Civ5Icon.ResWhale.png', label: 'ResWhale' },
    ICON_RES_WHEAT: { url: '/images/Civ5Icon.ResWheat.png', label: 'ResWheat' },
    ICON_RES_WINE: { url: '/images/Civ5Icon.ResWine.png', label: 'ResWine' },
    ICON_RESEARCH: { url: '/images/Civ5Icon.Research.png', label: 'Research' },
    ICON_RESISTANCE: { url: '/images/Civ5Icon.Resistance.png', label: 'Resistance' },
    ICON_SPY: { url: '/images/Civ5Icon.Spy.png', label: 'Spy' },
    ICON_STAR: { url: '/images/Civ5Icon.Star.png', label: 'Star' },
    ICON_STRENGTH: { url: '/images/Civ5Icon.Strength.png', label: 'Strength' },
    ICON_TEAM_10: { url: '/images/Civ5Icon.Team10.png', label: 'Team10' },
    ICON_TEAM_11: { url: '/images/Civ5Icon.Team11.png', label: 'Team11' },
    ICON_TEAM_1: { url: '/images/Civ5Icon.Team1.png', label: 'Team1' },
    ICON_TEAM_2: { url: '/images/Civ5Icon.Team2.png', label: 'Team2' },
    ICON_TEAM_3: { url: '/images/Civ5Icon.Team3.png', label: 'Team3' },
    ICON_TEAM_4: { url: '/images/Civ5Icon.Team4.png', label: 'Team4' },
    ICON_TEAM_5: { url: '/images/Civ5Icon.Team5.png', label: 'Team5' },
    ICON_TEAM_6: { url: '/images/Civ5Icon.Team6.png', label: 'Team6' },
    ICON_TEAM_7: { url: '/images/Civ5Icon.Team7.png', label: 'Team7' },
    ICON_TEAM_8: { url: '/images/Civ5Icon.Team8.png', label: 'Team8' },
    ICON_TEAM_9: { url: '/images/Civ5Icon.Team9.png', label: 'Team9' },
    ICON_TEAM_USA: { url: '/images/Civ5Icon.TeamUsa.png', label: 'TeamUsa' },
    ICON_TOURISM: { url: '/images/Civ5Icon.Tourism.png', label: 'Tourism' },
    ICON_TRADE: { url: '/images/Civ5Icon.Trade.png', label: 'Trade' },
    ICON_TRADE_WHITE: { url: '/images/Civ5Icon.TradeWhite.png', label: 'TradeWhite' },
    ICON_VIEW_CITY: { url: '/images/Civ5Icon.ViewCity.png', label: 'ViewCity' },
    ICON_WAR: { url: '/images/Civ5Icon.War.png', label: 'War' },
    ICON_WORKER: { url: '/images/Civ5Icon.Worker.png', label: 'Worker' },
    ICON_WTF1: { url: '/images/Civ5Icon.Wtf1.png', label: 'Wtf1' },
    ICON_WTF2: { url: '/images/Civ5Icon.Wtf2.png', label: 'Wtf2' },
};

export const ICON_PATTERN = /\[([A-Z0-9_]+)\]/g;

export function hasIcons(text: string): boolean {
    ICON_PATTERN.lastIndex = 0;
    return ICON_PATTERN.test(text);
}

export type TextSegment = string | { icon: IconDef; token: string };

export function parseIconMarkup(text: string): TextSegment[] {
    const segments: TextSegment[] = [];
    let last = 0;
    const re = /\[([A-Z0-9_]+)\]/g;
    let m: RegExpExecArray | null;

    while ((m = re.exec(text)) !== null) {
        if (m.index > last) {
            segments.push(text.slice(last, m.index));
        }
        const key = m[1];
        const def = ICON_MARKUPS[key];
        if (def) {
            segments.push({ icon: def, token: m[0] });
        } else {
            segments.push(m[0]);
        }
        last = m.index + m[0].length;
    }

    if (last < text.length) {
        segments.push(text.slice(last));
    }

    return segments;
}
export interface CivDef {
    CivID: number;
    CityName: string;
    PrimaryColor: string;
    SecondaryColor: string;
    TextColor: string;
}
export const CIVILIZATION_DEFINES: Record<string, CivDef> = {
    CIVILIZATION_AMERICA: { CivID:0, CityName:'TXT_KEY_CITY_NAME_WASHINGTON', PrimaryColor:'#FFFFFF', SecondaryColor:'#1F3378', TextColor:'#FFF2F2' },
    CIVILIZATION_ARABIA: { CivID:1, CityName:'TXT_KEY_CITY_NAME_MECCA', PrimaryColor:'#92DD09', SecondaryColor:'#2B572D', TextColor:'#FFF2F2' },
    CIVILIZATION_AZTEC: { CivID:2, CityName:'TXT_KEY_CITY_NAME_TENOCHTITLAN', PrimaryColor:'#88EED4', SecondaryColor:'#A13922', TextColor:'#FFF2F2' },
    CIVILIZATION_CHINA: { CivID:3, CityName:'TXT_KEY_CITY_NAME_BEIJING', PrimaryColor:'#FFFFFF', SecondaryColor:'#009452', TextColor:'#FFF2F2' },
    CIVILIZATION_EGYPT: { CivID:4, CityName:'TXT_KEY_CITY_NAME_THEBES', PrimaryColor:'#5200D0', SecondaryColor:'#FFFB03', TextColor:'#FFF2F2' },
    CIVILIZATION_ENGLAND: { CivID:5, CityName:'TXT_KEY_CITY_NAME_LONDON', PrimaryColor:'#FFFFFF', SecondaryColor:'#6C0200', TextColor:'#FFF2F2' },
    CIVILIZATION_FRANCE: { CivID:6, CityName:'TXT_KEY_CITY_NAME_PARIS', PrimaryColor:'#EBEB8A', SecondaryColor:'#418DFD', TextColor:'#FFF2F2' },
    CIVILIZATION_GERMANY: { CivID:7, CityName:'TXT_KEY_CITY_NAME_BERLIN', PrimaryColor:'#242B20', SecondaryColor:'#B3B1B8', TextColor:'#FFF2F2' },
    CIVILIZATION_GREECE: { CivID:8, CityName:'TXT_KEY_CITY_NAME_ATHENS', PrimaryColor:'#418DFD', SecondaryColor:'#FFFFFF', TextColor:'#FFF2F2' },
    CIVILIZATION_INDIA: { CivID:9, CityName:'TXT_KEY_CITY_NAME_DELHI', PrimaryColor:'#FF9931', SecondaryColor:'#128706', TextColor:'#FFF2F2' },
    CIVILIZATION_IROQUOIS: { CivID:10, CityName:'TXT_KEY_IROQ_CITY_NAME_ONONDAGA', PrimaryColor:'#FBC981', SecondaryColor:'#415656', TextColor:'#FFF2F2' },
    CIVILIZATION_JAPAN: { CivID:11, CityName:'TXT_KEY_CITY_NAME_KYOTO', PrimaryColor:'#B80000', SecondaryColor:'#FFFFFF', TextColor:'#FFF2F2' },
    CIVILIZATION_OTTOMAN: { CivID:12, CityName:'TXT_KEY_CITY_NAME_ISTANBUL', PrimaryColor:'#12521E', SecondaryColor:'#F7F8C7', TextColor:'#FFF2F2' },
    CIVILIZATION_PERSIA: { CivID:13, CityName:'TXT_KEY_CITY_NAME_PERSEPOLIS', PrimaryColor:'#F5E637', SecondaryColor:'#B00703', TextColor:'#FFF2F2' },
    CIVILIZATION_ROME: { CivID:14, CityName:'TXT_KEY_CITY_NAME_ROME', PrimaryColor:'#EFC600', SecondaryColor:'#460076', TextColor:'#FFF2F2' },
    CIVILIZATION_RUSSIA: { CivID:15, CityName:'TXT_KEY_CITY_NAME_MOSCOW', PrimaryColor:'#000000', SecondaryColor:'#EEB400', TextColor:'#FFF2F2' },
    CIVILIZATION_SIAM: { CivID:16, CityName:'TXT_KEY_SIAM_CITY_NAME_SUKHOTHAI', PrimaryColor:'#B00703', SecondaryColor:'#F5E637', TextColor:'#FFF2F2' },
    CIVILIZATION_SONGHAI: { CivID:17, CityName:'TXT_KEY_SONG_CITY_NAME_GAO', PrimaryColor:'#5A0009', SecondaryColor:'#D59113', TextColor:'#FFF2F2' },
    CIVILIZATION_MINOR: { CivID:18, CityName:'TXT_KEY_CITY_NAME_CHEROKEE', PrimaryColor:'#000000', SecondaryColor:'#E5E5E5', TextColor:'#C2B164' },
    CIVILIZATION_BARBARIAN: { CivID:19, CityName:'TXT_KEY_CITY_NAME_CHEROKEE', PrimaryColor:'#B70000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    CIVILIZATION_MONGOL: { CivID:20, CityName:'TXT_KEY_CITY_NAME_KARAKORUM', PrimaryColor:'#FF7800', SecondaryColor:'#510008', TextColor:'#FFF2F2' },
    CIVILIZATION_INCA: { CivID:21, CityName:'TXT_KEY_CITY_NAME_CUSCO', PrimaryColor:'#069F77', SecondaryColor:'#FFB821', TextColor:'#FFF2F2' },
    CIVILIZATION_SPAIN: { CivID:22, CityName:'TXT_KEY_CITY_NAME_MADRID', PrimaryColor:'#FFA8A8', SecondaryColor:'#531A1A', TextColor:'#FFF2F2' },
    CIVILIZATION_POLYNESIA: { CivID:23, CityName:'TXT_KEY_CITY_NAME_HONOLULU', PrimaryColor:'#FFFF4A', SecondaryColor:'#D95800', TextColor:'#FFF2F2' },
    CIVILIZATION_DENMARK: { CivID:24, CityName:'TXT_KEY_CITY_NAME_COPENHAGEN', PrimaryColor:'#EFE7B3', SecondaryColor:'#6C2A14', TextColor:'#FFF2F2' },
    CIVILIZATION_KOREA: { CivID:25, CityName:'TXT_KEY_CITY_NAME_SEOUL', PrimaryColor:'#FF0000', SecondaryColor:'#1A2060', TextColor:'#FFF2F2' },
    CIVILIZATION_BABYLON: { CivID:26, CityName:'TXT_KEY_CITY_NAME_BABYLON', PrimaryColor:'#C8F8FF', SecondaryColor:'#2B5161', TextColor:'#FFF2F2' },
    CIVILIZATION_AUSTRIA: { CivID:27, CityName:'TXT_KEY_CITY_NAME_VIENNA', PrimaryColor:'#FFFFFF', SecondaryColor:'#EA0000', TextColor:'#FFF2F2' },
    CIVILIZATION_BYZANTIUM: { CivID:28, CityName:'TXT_KEY_CITY_NAME_CONSTANTINOPLE', PrimaryColor:'#3C006C', SecondaryColor:'#71A1E8', TextColor:'#FFF2F2' },
    CIVILIZATION_CARTHAGE: { CivID:29, CityName:'TXT_KEY_CITY_NAME_CARTHAGE', PrimaryColor:'#500088', SecondaryColor:'#CCCCCC', TextColor:'#FFF2F2' },
    CIVILIZATION_CELTS: { CivID:30, CityName:'TXT_KEY_CITY_NAME_EDINBURGH', PrimaryColor:'#93A9FF', SecondaryColor:'#155B3E', TextColor:'#FFF2F2' },
    CIVILIZATION_ETHIOPIA: { CivID:31, CityName:'TXT_KEY_CITY_NAME_ADDISABABA', PrimaryColor:'#FF2D2D', SecondaryColor:'#01270E', TextColor:'#FFF2F2' },
    CIVILIZATION_HUNS: { CivID:32, CityName:'TXT_KEY_CITY_NAME_ATTILAS_COURT', PrimaryColor:'#450003', SecondaryColor:'#B3B1A3', TextColor:'#FFF2F2' },
    CIVILIZATION_MAYA: { CivID:33, CityName:'TXT_KEY_CITY_NAME_PALENQUE', PrimaryColor:'#173E41', SecondaryColor:'#C58C62', TextColor:'#FFF2F2' },
    CIVILIZATION_NETHERLANDS: { CivID:34, CityName:'TXT_KEY_CITY_NAME_AMSTERDAM', PrimaryColor:'#FFFFFF', SecondaryColor:'#FF8F00', TextColor:'#FFF2F2' },
    CIVILIZATION_SWEDEN: { CivID:35, CityName:'TXT_KEY_CITY_NAME_STOCKHOLM', PrimaryColor:'#F8F602', SecondaryColor:'#0707A5', TextColor:'#FFF2F2' },
    CIVILIZATION_ASSYRIA: { CivID:36, CityName:'TXT_KEY_CITY_NAME_ASSUR', PrimaryColor:'#FFA90D', SecondaryColor:'#FFF4AD', TextColor:'#FFF2F2' },
    CIVILIZATION_BRAZIL: { CivID:37, CityName:'TXT_KEY_CITY_NAME_RIO_DE_JANEIRO', PrimaryColor:'#29532C', SecondaryColor:'#96DE0A', TextColor:'#FFF2F2' },
    CIVILIZATION_INDONESIA: { CivID:38, CityName:'TXT_KEY_CITY_NAME_JAKARTA', PrimaryColor:'#9F2F1D', SecondaryColor:'#6FD3D9', TextColor:'#FFF2F2' },
    CIVILIZATION_MOROCCO: { CivID:39, CityName:'TXT_KEY_CITY_NAME_MARRAKECH', PrimaryColor:'#28B350', SecondaryColor:'#900200', TextColor:'#FFF2F2' },
    CIVILIZATION_POLAND: { CivID:40, CityName:'TXT_KEY_CITY_NAME_WARSAW', PrimaryColor:'#390000', SecondaryColor:'#F40500', TextColor:'#FFF2F2' },
    CIVILIZATION_PORTUGAL: { CivID:41, CityName:'TXT_KEY_CITY_NAME_LISBON', PrimaryColor:'#04147C', SecondaryColor:'#FFFFFF', TextColor:'#FFF2F2' },
    CIVILIZATION_SHOSHONE: { CivID:42, CityName:'TXT_KEY_CITY_NAME_MOSON_KAHNI', PrimaryColor:'#18F0CD', SecondaryColor:'#493B2E', TextColor:'#FFF2F2' },
    CIVILIZATION_VENICE: { CivID:43, CityName:'TXT_KEY_CITY_NAME_VENICE', PrimaryColor:'#FFFED7', SecondaryColor:'#6621A2', TextColor:'#FFF2F2' },
    CIVILIZATION_ZULU: { CivID:44, CityName:'TXT_KEY_CITY_NAME_ULUNDI', PrimaryColor:'#6A3218', SecondaryColor:'#FFE8D6', TextColor:'#FFF2F2' },
    MINOR_CIV_BRATISLAVA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BRATISLAVA', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_BUDAPEST: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BUDAPEST', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_GENEVA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_GENEVA', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_RIGA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_RIGA', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_GENOA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_GENOA', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_FLORENCE: { CivID:18, CityName:'TXT_KEY_CITYSTATE_FLORENCE', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_RAGUSA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_RAGUSA', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_SYDNEY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_SYDNEY', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_QUEBEC_CITY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_QUEBEC_CITY', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_BUCHAREST: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BUCHAREST', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_BELGRADE: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BELGRADE', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_BRUSSELS: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BRUSSELS', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MONACO: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MONACO', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_KATHMANDU: { CivID:18, CityName:'TXT_KEY_CITYSTATE_KATHMANDU', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_HANOI: { CivID:18, CityName:'TXT_KEY_CITYSTATE_HANOI', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_LHASA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_LHASA', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_ALMATY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_ALMATY', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_KUALA_LUMPUR: { CivID:18, CityName:'TXT_KEY_CITYSTATE_KUALA_LUMPUR', PrimaryColor:'#FFFF7F', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_SINGAPORE: { CivID:18, CityName:'TXT_KEY_CITYSTATE_SINGAPORE', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_PANAMA_CITY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_PANAMA_CITY', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_CAPE_TOWN: { CivID:18, CityName:'TXT_KEY_CITYSTATE_CAPE_TOWN', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_SIDON: { CivID:18, CityName:'TXT_KEY_CITYSTATE_SIDON', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_TYRE: { CivID:18, CityName:'TXT_KEY_CITYSTATE_TYRE', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_ANTWERP: { CivID:18, CityName:'TXT_KEY_CITYSTATE_ANTWERP', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_CAHOKIA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_CAHOKIA', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_COLOMBO: { CivID:18, CityName:'TXT_KEY_CITYSTATE_COLOMBO', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_HONG_KONG: { CivID:18, CityName:'TXT_KEY_CITYSTATE_HONG_KONG', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_ORMUS: { CivID:18, CityName:'TXT_KEY_CITYSTATE_ORMUS', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_JERUSALEM: { CivID:18, CityName:'TXT_KEY_CITYSTATE_JERUSALEM', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_LA_VENTA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_LA_VENTA', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_VANCOUVER: { CivID:18, CityName:'TXT_KEY_CITYSTATE_VANCOUVER', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MANILA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MANILA', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_ANTANANARIVO: { CivID:18, CityName:'TXT_KEY_CITYSTATE_ANTANANARIVO', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MILAN: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MILAN', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MOMBASA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MOMBASA', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_PRAGUE: { CivID:18, CityName:'TXT_KEY_CITYSTATE_PRAGUE', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_VALLETTA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_VALLETTA', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_VATICAN_CITY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_VATICAN_CITY', PrimaryColor:'#B2B2B2', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_WITTENBERG: { CivID:18, CityName:'TXT_KEY_CITYSTATE_WITTENBERG', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_YEREVAN: { CivID:18, CityName:'TXT_KEY_CITYSTATE_YEREVAN', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_ZANZIBAR: { CivID:18, CityName:'TXT_KEY_CITYSTATE_ZANZIBAR', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_ZURICH: { CivID:18, CityName:'TXT_KEY_CITYSTATE_ZURICH', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_SAMARKAND: { CivID:18, CityName:'TXT_KEY_CITYSTATE_SAMARKAND', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MALACCA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MALACCA', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MOGADISHU: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MOGADISHU', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_BYBLOS: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BYBLOS', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_KYZYL: { CivID:18, CityName:'TXT_KEY_CITYSTATE_KYZYL', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_IFE: { CivID:18, CityName:'TXT_KEY_CITYSTATE_IFE', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_KIEV: { CivID:18, CityName:'TXT_KEY_CITYSTATE_KIEV', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_BUENOS_AIRES: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BUENOS_AIRES', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MBANZA_KONGO: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MBANZA_KONGO', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_KABUL: { CivID:18, CityName:'TXT_KEY_CITYSTATE_KABUL', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_SOFIA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_SOFIA', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_UR: { CivID:18, CityName:'TXT_KEY_CITYSTATE_UR', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MELBOURNE: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MELBOURNE', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_BOGOTA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BOGOTA', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_VILNIUS: { CivID:18, CityName:'TXT_KEY_CITYSTATE_VILNIUS', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_WELLINGTON: { CivID:18, CityName:'TXT_KEY_CITYSTATE_WELLINGTON', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MOHENJO_DARO: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MOHENJO_DARO', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_REYKJAVIK: { CivID:18, CityName:'TXT_KEY_CITYSTATE_REYKJAVIK', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_PHAISTOS: { CivID:18, CityName:'TXT_KEY_CITYSTATE_PHAISTOS', PrimaryColor:'#C456FF', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MARIENBURG: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MARIENBURG', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_MEWAR: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MEWAR', PrimaryColor:'#FF4C4C', SecondaryColor:'#000000', TextColor:'#FF4B6A' },
    MINOR_CIV_TROY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_TROY', PrimaryColor:'#7CE000', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MUSCAT: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MUSCAT', PrimaryColor:'#FFFF2B', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_ARMAGH: { CivID:18, CityName:'TXT_KEY_CITYSTATE_ARMAGH', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_KANDY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_KANDY', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_NAZCA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_NAZCA', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_CHINGUETTY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_CHINGUETTY', PrimaryColor:'#E5E5E5', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_BOLOGNA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BOLOGNA', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MITLA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MITLA', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_NALANDA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_NALANDA', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_TAIPEI: { CivID:18, CityName:'TXT_KEY_CITYSTATE_TAIPEI', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_TARUGA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_TARUGA', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_HATTUSA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_HATTUSA', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_KHIVA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_KHIVA', PrimaryColor:'#11CCF4', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_ANGKOR: { CivID:18, CityName:'TXT_KEY_CITYSTATE_ANGKOR', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_BASEL: { CivID:18, CityName:'TXT_KEY_CITYSTATE_BASEL', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_DHAKA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_DHAKA', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_JOHANNESBURG: { CivID:18, CityName:'TXT_KEY_CITYSTATE_JOHANNESBURG', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_LUXEMBOURG: { CivID:18, CityName:'TXT_KEY_CITYSTATE_LUXEMBOURG', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_MEXICO_CITY: { CivID:18, CityName:'TXT_KEY_CITYSTATE_MEXICO_CITY', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_PETRA: { CivID:18, CityName:'TXT_KEY_CITYSTATE_PETRA', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
    MINOR_CIV_STAVANGER: { CivID:18, CityName:'TXT_KEY_CITYSTATE_STAVANGER', PrimaryColor:'#E5A551', SecondaryColor:'#000000', TextColor:'#C2B164' },
}
